- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    filename: "elastic-7.x"

- name: Update apt cache
  apt: update_cache=yes

- name: Install Elasticsearch
  apt:
    name: "elasticsearch={{ elasticsearch_version }}"
    state: present

- name: Configure elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: "0640"
  notify: Restart Elasticsearch

- name: Enable + start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: true
    state: started
